name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Restore dependency cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ./vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: |
          go mod download

      - name: Save dependency cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ./vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6

      - name: Test
        run: go test -v ./...
